In [7]:
import numpy as np

# 创建两个简单的数组
x = np.array([1, 2, 3, 3, 4])
y = np.array([4, 5, 6, 3, 1])

In [8]:
# 计算皮尔逊相关系数
r = np.corrcoef(x, y)[0, 1]


In [9]:
# 显示结果
r

-0.5015568278463085

In [10]:
m = np.corrcoef(x, y)
m

array([[ 1.        , -0.50155683],
       [-0.50155683,  1.        ]])

In [20]:
import pandas as pd

# 创建一个简单的 DataFrame
data = {'A': [1.1, 22.6, 3, 3, 4], 'B': [4, 50.2, 6, 3, 1]}
df = pd.DataFrame(data)

# 计算 'A' 列和 'B' 列之间的皮尔逊相关系数
r = df['A'].corr(df['B'])

# 显示结果
print(r)

0.9847762934788714


# 下面才是计算我们需要的数据

In [1]:
import anndata
import pandas as pd

In [2]:
adata = anndata.read_h5ad('data-processing/integrated-no-filtration-mouse.h5ad')
adata

AnnData object with n_obs × n_vars = 1749 × 10391
    obs: 'Sample', 'doublet', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'pct_counts_ribo', 'cell_label', '_scvi_batch', '_scvi_labels', 'tsne_0', 'tsne_1', 'leiden', '_scvi_raw_norm_scaling'
    var: 'n_cells'
    uns: 'Sample_colors', '_scvi_manager_uuid', '_scvi_uuid', 'cell_label_colors', 'leiden', 'leiden_colors', 'log1p', 'markers', 'markers_scvi', 'neighbors', 'rank_genes_groups', 'tsne'
    obsm: 'X_pca', 'X_scVI', 'X_tsne', '_scvi_extra_categorical_covs', '_scvi_extra_continuous_covs'
    layers: 'counts', 'scvi_normalized'
    obsp: 'connectivities', 'distances'

In [10]:
adata.X.toarray()

array([[0.        , 0.        , 0.7046421 , ..., 0.7046421 , 0.        ,
        1.1139097 ],
       [0.8410236 , 0.8410236 , 0.        , ..., 0.8410236 , 0.8410236 ,
        0.        ],
       [0.        , 0.        , 0.74593014, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [13]:
adata.layers['counts'].toarray()

array([[0., 0., 1., ..., 1., 0., 2.],
       [1., 1., 0., ..., 1., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [16]:
adata.layers['scvi_normalized']

array([[0.06973211, 0.15309328, 0.51507634, ..., 0.47246483, 0.46111214,
        0.68825686],
       [0.20074664, 0.27079445, 0.24380021, ..., 0.84877264, 0.5825992 ,
        1.1420248 ],
       [0.2998766 , 0.6604389 , 0.33520782, ..., 0.27335444, 0.8291221 ,
        0.17239672],
       ...,
       [0.80821776, 0.33082455, 0.03574816, ..., 0.4729761 , 1.0744681 ,
        0.9628242 ],
       [0.24510114, 0.2111673 , 0.03739965, ..., 0.62621516, 0.41151962,
        2.8850958 ],
       [0.57671577, 0.1786939 , 0.01946945, ..., 0.45297557, 0.3057082 ,
        0.8801038 ]], dtype=float32)

In [17]:
gene_var_label = adata.var.index
gene_var_label

Index(['0610007P14Rik', '0610009B22Rik', '0610009E02Rik', '0610009L18Rik',
       '0610009O20Rik', '0610010F05Rik', '0610010K14Rik', '0610011F06Rik',
       '0610012G03Rik', '0610030E20Rik',
       ...
       'Zufsp', 'Zw10', 'Zwint', 'Zxdb', 'Zxdc', 'Zyg11b', 'Zyx', 'Zzef1',
       'Zzz3', 'l7Rn6'],
      dtype='object', length=10391)

In [18]:
gene_var_label_list = gene_var_label.tolist()
gene_var_label_list

['0610007P14Rik',
 '0610009B22Rik',
 '0610009E02Rik',
 '0610009L18Rik',
 '0610009O20Rik',
 '0610010F05Rik',
 '0610010K14Rik',
 '0610011F06Rik',
 '0610012G03Rik',
 '0610030E20Rik',
 '0610037L13Rik',
 '0610040J01Rik',
 '1110001J03Rik',
 '1110002L01Rik',
 '1110004E09Rik',
 '1110004F10Rik',
 '1110008F13Rik',
 '1110008L16Rik',
 '1110008P14Rik',
 '1110012L19Rik',
 '1110020A21Rik',
 '1110032A03Rik',
 '1110034G24Rik',
 '1110037F02Rik',
 '1110038B12Rik',
 '1110038F14Rik',
 '1110051M20Rik',
 '1110059E24Rik',
 '1110059G10Rik',
 '1110065P20Rik',
 '1190002N15Rik',
 '1190007I07Rik',
 '1300002E11Rik',
 '1500009L16Rik',
 '1500011B03Rik',
 '1500011K16Rik',
 '1500026H17Rik',
 '1520401A03Rik',
 '1600002H07Rik',
 '1600002K03Rik',
 '1600012H06Rik',
 '1600014C10Rik',
 '1600020E01Rik',
 '1700017B05Rik',
 '1700019D03Rik',
 '1700020I14Rik',
 '1700021F05Rik',
 '1700023F06Rik',
 '1700025G04Rik',
 '1700029J07Rik',
 '1700030K09Rik',
 '1700037C18Rik',
 '1700037H04Rik',
 '1700047I17Rik2',
 '1700049G17Rik',
 '1700073

In [26]:
# 上一步中获得了基因名称的list，现在将这个基因的list转换成索引和列名的DataFrame
cpp_result_matrix = pd.DataFrame(index=gene_var_label_list, columns=gene_var_label_list)
cpp_result_matrix

0610007P14Rik 0610009B22Rik 0610009E02Rik 0610009L18Rik  \
0610007P14Rik           NaN           NaN           NaN           NaN   
0610009B22Rik           NaN           NaN           NaN           NaN   
0610009E02Rik           NaN           NaN           NaN           NaN   
0610009L18Rik           NaN           NaN           NaN           NaN   
0610009O20Rik           NaN           NaN           NaN           NaN   
...                     ...           ...           ...           ...   
Zyg11b                  NaN           NaN           NaN           NaN   
Zyx                     NaN           NaN           NaN           NaN   
Zzef1                   NaN           NaN           NaN           NaN   
Zzz3                    NaN           NaN           NaN           NaN   
l7Rn6                   NaN           NaN           NaN           NaN   

              0610009O20Rik 0610010F05Rik 0610010K14Rik 0610011F06Rik  \
0610007P14Rik           NaN           NaN           NaN           NaN   
0610009B22Rik           NaN           NaN           NaN           NaN   
0610009E02Rik           NaN           NaN           NaN           NaN   
0610009L18Rik           NaN           NaN           NaN           NaN   
0610009O20Rik           NaN           NaN           NaN           NaN   
...                     ...           ...           ...           ...   
Zyg11b                  NaN           NaN           NaN           NaN   
Zyx                     NaN           NaN           NaN           NaN   
Zzef1                   NaN           NaN           NaN           NaN   
Zzz3                    NaN           NaN           NaN           NaN   
l7Rn6                   NaN           NaN           NaN           NaN   

              0610012G03Rik 0610030E20Rik  ... Zufsp Zw10 Zwint Zxdb Zxdc  \
0610007P14Rik           NaN           NaN  ...   NaN  NaN   NaN  NaN  NaN   
0610009B22Rik           NaN           NaN  ...   NaN  NaN   NaN  NaN  NaN   
0610009E02Rik           NaN           NaN  ...   NaN  NaN   NaN  NaN  NaN   
0610009L18Rik           NaN           NaN  ...   NaN  NaN   NaN  NaN  NaN   
0610009O20Rik           NaN           NaN  ...   NaN  NaN   NaN  NaN  NaN   
...                     ...           ...  ...   ...  ...   ...  ...  ...   
Zyg11b                  NaN           NaN  ...   NaN  NaN   NaN  NaN  NaN   
Zyx                     NaN           NaN  ...   NaN  NaN   NaN  NaN  NaN   
Zzef1                   NaN           NaN  ...   NaN  NaN   NaN  NaN  NaN   
Zzz3                    NaN           NaN  ...   NaN  NaN   NaN  NaN  NaN   
l7Rn6                   NaN           NaN  ...   NaN  NaN   NaN  NaN  NaN   

              Zyg11b  Zyx Zzef1 Zzz3 l7Rn6  
0610007P14Rik    NaN  NaN   NaN  NaN   NaN  
0610009B22Rik    NaN  NaN   NaN  NaN   NaN  
0610009E02Rik    NaN  NaN   NaN  NaN   NaN  
0610009L18Rik    NaN  NaN   NaN  NaN   NaN  
0610009O20Rik    NaN  NaN   NaN  NaN   NaN  
...              ...  ...   ...  ...   ...  
Zyg11b           NaN  NaN   NaN  NaN   NaN  
Zyx              NaN  NaN   NaN  NaN   NaN  
Zzef1            NaN  NaN   NaN  NaN   NaN  
Zzz3             NaN  NaN   NaN  NaN   NaN  
l7Rn6            NaN  NaN   NaN  NaN   NaN  

[10391 rows x 10391 columns]

In [20]:
import pandas as pd

In [24]:
# cell_gene_X = pd.DataFrame(adata.layers['counts'].toarray())
cell_gene_X = pd.DataFrame(adata.X.toarray())
cell_gene_X

0         1         2      3      4      5      6         7      \
0     0.000000  0.000000  0.704642    0.0    0.0    0.0    0.0  0.704642   
1     0.841024  0.841024  0.000000    0.0    0.0    0.0    0.0  0.000000   
2     0.000000  0.000000  0.745930    0.0    0.0    0.0    0.0  0.000000   
3     0.653543  0.000000  0.653543    0.0    0.0    0.0    0.0  0.000000   
4     0.000000  0.000000  0.000000    0.0    0.0    0.0    0.0  0.000000   
...        ...       ...       ...    ...    ...    ...    ...       ...   
1744  0.000000  0.000000  0.000000    0.0    0.0    0.0    0.0  0.000000   
1745  0.000000  0.000000  0.000000    0.0    0.0    0.0    0.0  0.000000   
1746  0.000000  0.000000  0.000000    0.0    0.0    0.0    0.0  0.000000   
1747  0.000000  0.000000  0.000000    0.0    0.0    0.0    0.0  0.000000   
1748  0.000000  0.000000  0.000000    0.0    0.0    0.0    0.0  0.000000   

         8      9      ...     10381  10382     10383  10384     10385  10386  \
0     1.113910    0.0  ...  0.000000    0.0  0.000000    0.0  0.704642    0.0   
1     0.841024    0.0  ...  0.000000    0.0  0.841024    0.0  0.000000    0.0   
2     0.000000    0.0  ...  0.000000    0.0  1.168388    0.0  0.000000    0.0   
3     0.653543    0.0  ...  0.653543    0.0  0.653543    0.0  0.000000    0.0   
4     0.000000    0.0  ...  0.000000    0.0  0.000000    0.0  0.000000    0.0   
...        ...    ...  ...       ...    ...       ...    ...       ...    ...   
1744  0.000000    0.0  ...  0.000000    0.0  0.000000    0.0  0.000000    0.0   
1745  0.000000    0.0  ...  0.000000    0.0  2.464574    0.0  0.000000    0.0   
1746  0.000000    0.0  ...  0.000000    0.0  1.939084    0.0  0.000000    0.0   
1747  0.000000    0.0  ...  0.000000    0.0  0.000000    0.0  0.000000    0.0   
1748  0.000000    0.0  ...  0.000000    0.0  1.995690    0.0  0.000000    0.0   

         10387     10388     10389     10390  
0     0.000000  0.704642  0.000000  1.113910  
1     0.000000  0.841024  0.841024  0.000000  
2     0.000000  0.000000  0.000000  0.000000  
3     0.000000  0.000000  0.000000  0.653543  
4     0.000000  0.000000  0.000000  0.000000  
...        ...       ...       ...       ...  
1744  0.000000  0.000000  0.000000  0.000000  
1745  0.000000  0.000000  2.464574  0.000000  
1746  0.000000  0.000000  0.000000  0.000000  
1747  2.054472  0.000000  0.000000  0.000000  
1748  0.000000  0.000000  0.000000  0.000000  

[1749 rows x 10391 columns]

In [25]:
corr_result = cell_gene_X.corr()
corr_result

KeyboardInterrupt: 

In [72]:
b = corr_result[corr_result > 0.9]

In [73]:
b.sum(axis=0)

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ... 
13546    1.0
13547    1.0
13548    1.0
13549    1.0
13550    1.0
Length: 13551, dtype: float64

In [29]:
# 下面跑正则化版本
cell_gene_X_norm = pd.DataFrame(adata.layers['scvi_normalized'])
cell_gene_X_norm

0         1         2         3         4         5         6      \
0     0.069732  0.153093  0.515076  0.049392  0.476986  0.389082  0.060317   
1     0.200747  0.270794  0.243800  0.085502  0.458941  0.533871  0.045120   
2     0.299877  0.660439  0.335208  0.073299  0.120608  0.466143  0.269413   
3     0.102097  0.516949  0.693050  0.012044  0.297955  0.165848  0.077809   
4     0.276601  0.845343  0.040151  0.033707  0.773441  0.024128  0.097982   
...        ...       ...       ...       ...       ...       ...       ...   
1744  0.121323  0.588136  0.449547  0.049985  0.105681  0.475687  0.580270   
1745  0.090385  0.531650  0.393714  0.055427  0.138092  0.764761  0.789061   
1746  0.808218  0.330825  0.035748  0.052865  0.559054  0.999626  0.491436   
1747  0.245101  0.211167  0.037400  0.006365  0.203482  0.596077  0.586518   
1748  0.576716  0.178694  0.019469  0.023422  0.125960  0.379730  0.441616   

         7         8         9      ...     10381     10382     10383  \
0     0.907990  0.290609  0.071577  ...  0.034442  0.917246  0.655143   
1     0.699856  0.407266  0.130871  ...  0.044981  0.483097  0.587575   
2     0.409467  0.220384  0.519334  ...  0.186336  0.145861  0.975991   
3     0.773591  0.332129  0.206533  ...  0.087363  0.815621  1.606236   
4     0.792943  0.618983  0.347271  ...  0.023665  0.116187  1.016101   
...        ...       ...       ...  ...       ...       ...       ...   
1744  0.448002  0.357790  0.023218  ...  0.005469  1.644867  1.783308   
1745  0.704292  0.444463  0.036753  ...  0.006395  1.766172  1.624953   
1746  0.452542  1.264179  0.294028  ...  0.029626  0.255300  1.788890   
1747  0.167588  0.580223  0.092189  ...  0.088158  0.271914  4.240451   
1748  0.038645  1.454984  0.060209  ...  0.008105  0.170067  3.686076   

         10384     10385     10386     10387     10388     10389     10390  
0     0.037520  0.136236  0.189807  0.644773  0.472465  0.461112  0.688257  
1     0.065559  0.466772  0.363481  0.765396  0.848773  0.582599  1.142025  
2     0.076761  0.289051  1.461041  0.278816  0.273354  0.829122  0.172397  
3     0.076482  0.125218  0.400721  0.404820  0.143503  0.968766  0.516628  
4     0.251681  0.237220  0.457873  0.975447  0.204224  0.902102  0.997966  
...        ...       ...       ...       ...       ...       ...       ...  
1744  0.042859  0.704189  0.464537  0.508399  0.342687  0.715842  1.236295  
1745  0.060939  0.642285  0.432808  0.709543  0.384342  0.617884  1.615472  
1746  0.192083  0.899434  0.417456  0.861601  0.472976  1.074468  0.962824  
1747  0.366887  0.712416  0.995104  2.351725  0.626215  0.411520  2.885096  
1748  0.142367  0.321083  1.402668  1.147189  0.452976  0.305708  0.880104  

[1749 rows x 10391 columns]

In [30]:
corr_result_norm = cell_gene_X_norm.corr()
corr_result_norm

0         1         2         3         4         5         6      \
0      1.000000  0.163351 -0.183443 -0.039735 -0.090042 -0.133749  0.041896   
1      0.163351  1.000000  0.153439  0.280461 -0.061584  0.062891 -0.088999   
2     -0.183443  0.153439  1.000000  0.338401 -0.212104  0.158121  0.054817   
3     -0.039735  0.280461  0.338401  1.000000  0.065609  0.069211  0.039512   
4     -0.090042 -0.061584 -0.212104  0.065609  1.000000  0.067106 -0.137877   
...         ...       ...       ...       ...       ...       ...       ...   
10386  0.094013  0.225214 -0.028234 -0.059064  0.049963  0.086546 -0.015287   
10387  0.326305 -0.017723 -0.179525 -0.067925 -0.194053 -0.097310  0.015381   
10388  0.160103 -0.178553  0.137030 -0.111386 -0.048006  0.390447  0.388027   
10389  0.008228 -0.015086  0.175906 -0.124034 -0.027563  0.319188  0.126307   
10390 -0.002310  0.185272 -0.117700  0.069197 -0.086336 -0.050414 -0.012414   

          7         8         9      ...     10381     10382     10383  \
0     -0.154340  0.231174  0.091477  ...  0.364649 -0.143748  0.212514   
1      0.287932  0.056497  0.222687  ...  0.002199  0.019610  0.033944   
2      0.205645 -0.148981  0.000257  ... -0.085750  0.405416  0.024573   
3      0.417701 -0.046557  0.279267  ... -0.070028  0.154913 -0.091073   
4      0.302125 -0.008795  0.246818  ... -0.044844 -0.357939 -0.204120   
...         ...       ...       ...  ...       ...       ...       ...   
10386 -0.091343 -0.033116  0.245303  ...  0.159824  0.053086  0.205791   
10387 -0.290090  0.219353 -0.006669  ...  0.134324 -0.101858  0.289210   
10388 -0.017626 -0.119789 -0.121734  ...  0.240677  0.426804  0.206396   
10389  0.067171 -0.038678 -0.026555  ...  0.036503  0.328491  0.087602   
10390 -0.023893  0.130307 -0.111367  ... -0.146215  0.008941  0.084581   

          10384     10385     10386     10387     10388     10389     10390  
0     -0.040085  0.047989  0.094013  0.326305  0.160103  0.008228 -0.002310  
1      0.195882  0.131447  0.225214 -0.017723 -0.178553 -0.015086  0.185272  
2      0.103115  0.426549 -0.028234 -0.179525  0.137030  0.175906 -0.117700  
3      0.000904  0.044182 -0.059064 -0.067925 -0.111386 -0.124034  0.069197  
4      0.046932 -0.167421  0.049963 -0.194053 -0.048006 -0.027563 -0.086336  
...         ...       ...       ...       ...       ...       ...       ...  
10386  0.330274  0.250882  1.000000 -0.101113  0.149970  0.228059 -0.100187  
10387 -0.088721 -0.175275 -0.101113  1.000000 -0.092127 -0.140637  0.355327  
10388  0.171774  0.408141  0.149970 -0.092127  1.000000  0.662150 -0.265291  
10389  0.100388  0.568339  0.228059 -0.140637  0.662150  1.000000 -0.261322  
10390 -0.082690 -0.100015 -0.100187  0.355327 -0.265291 -0.261322  1.000000  

[10391 rows x 10391 columns]

In [31]:
a = corr_result_norm[corr_result_norm > 0.7]

In [32]:
a.sum(axis=0)

0         1.000000
1         1.000000
2         1.000000
3         1.000000
4         1.000000
           ...    
10386     1.000000
10387     1.000000
10388    75.635935
10389     5.260135
10390     1.000000
Length: 10391, dtype: float64

In [33]:
import anndata

In [34]:
adata_pcc_norm = anndata.AnnData(corr_result_norm)

C:\Users\25363\anaconda3\envs\scVI\lib\site-packages\anndata\_core\anndata.py:117: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
C:\Users\25363\anaconda3\envs\scVI\lib\site-packages\anndata\_core\anndata.py:117: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


In [35]:
adata_pcc_norm

AnnData object with n_obs × n_vars = 10391 × 10391

In [36]:
adata_pcc_norm.write_h5ad('data-processing/pcc-mouse-10391-dim-norm.h5ad')

In [111]:
corr_result[corr_result > 0.7].sum(axis=0)

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ... 
13546    1.0
13547    1.0
13548    1.0
13549    1.0
13550    1.0
Length: 13551, dtype: float64

In [37]:
adata1 = anndata.read_h5ad('data-processing/pcc-mouse-10391-dim-norm.h5ad')
adata1.X

array([[ 1.        ,  0.16335125, -0.18344343, ...,  0.1601034 ,
         0.00822847, -0.00230962],
       [ 0.16335125,  1.        ,  0.153439  , ..., -0.17855333,
        -0.01508599,  0.18527236],
       [-0.18344343,  0.153439  ,  1.        , ...,  0.13703033,
         0.17590557, -0.11769986],
       ...,
       [ 0.1601034 , -0.17855333,  0.13703033, ...,  1.        ,
         0.66215032, -0.26529083],
       [ 0.00822847, -0.01508599,  0.17590557, ...,  0.66215032,
         1.        , -0.26132152],
       [-0.00230962,  0.18527236, -0.11769986, ..., -0.26529083,
        -0.26132152,  1.        ]])

In [114]:
adata2 = anndata.read_h5ad('data-processing/pcc-human-13551-dim-no-norm.h5ad')
adata2.X

array([[ 1.00000000e+00, -5.56654121e-03, -4.18559652e-03, ...,
        -7.93384760e-04, -1.00835532e-02, -1.10846909e-02],
       [-5.56654121e-03,  1.00000000e+00, -4.68004773e-02, ...,
        -2.29759552e-02,  2.21057345e-02, -6.88133719e-02],
       [-4.18559652e-03, -4.68004773e-02,  1.00000000e+00, ...,
         9.61795426e-03,  1.56816980e-03,  1.17607465e-01],
       ...,
       [-7.93384760e-04, -2.29759552e-02,  9.61795426e-03, ...,
         1.00000000e+00,  9.16861254e-03, -1.41883027e-02],
       [-1.00835532e-02,  2.21057345e-02,  1.56816980e-03, ...,
         9.16861254e-03,  1.00000000e+00, -2.80056659e-02],
       [-1.10846909e-02, -6.88133719e-02,  1.17607465e-01, ...,
        -1.41883027e-02, -2.80056659e-02,  1.00000000e+00]])

In [119]:
import pandas as pd
import anndata
df1 = adata1.to_df()
df1

0         1         2         3         4         5         6  \
0      1.000000  0.127017  0.029844  0.129520  0.131204  0.032949 -0.097888   
1      0.127017  1.000000 -0.255027 -0.028819  0.502785  0.427996 -0.232413   
2      0.029844 -0.255027  1.000000  0.205872 -0.071567 -0.226827  0.073339   
3      0.129520 -0.028819  0.205872  1.000000  0.011931 -0.119074 -0.143302   
4      0.131204  0.502785 -0.071567  0.011931  1.000000  0.178093 -0.231005   
...         ...       ...       ...       ...       ...       ...       ...   
13546 -0.056780  0.296675 -0.095726 -0.132808  0.436061  0.081531 -0.276273   
13547 -0.214850 -0.332743  0.134546  0.509804 -0.141405 -0.359331 -0.013338   
13548  0.007842  0.079091 -0.104331 -0.054445  0.211014  0.138165 -0.307879   
13549 -0.045701  0.080246 -0.146242 -0.107237  0.104525  0.141659 -0.148224   
13550 -0.127980 -0.422945  0.301637  0.397015 -0.198180 -0.410683  0.245757   

              7         8         9  ...     13541     13542     13543  \
0      0.069752 -0.037234  0.037090  ... -0.159715  0.090146  0.070842   
1      0.271216  0.485316 -0.011073  ... -0.227877 -0.146029 -0.037553   
2     -0.182070 -0.235088 -0.236091  ...  0.072975  0.146704 -0.078576   
3     -0.106364 -0.225854  0.000588  ...  0.003409  0.140703 -0.158259   
4      0.049144  0.216368  0.126999  ... -0.077408  0.147980  0.139439   
...         ...       ...       ...  ...       ...       ...       ...   
13546  0.104323  0.342396  0.096886  ...  0.182228  0.237951  0.161289   
13547 -0.263748 -0.281375 -0.075323  ...  0.066649  0.112535 -0.159346   
13548  0.124768  0.081789  0.320304  ...  0.363814  0.087250  0.103774   
13549 -0.004133  0.089860  0.212151  ...  0.171016  0.168737  0.264627   
13550 -0.299270 -0.417542 -0.215186  ... -0.001296  0.067216 -0.113408   

          13544     13545     13546     13547     13548     13549     13550  
0      0.097528  0.158718 -0.056780 -0.214850  0.007842 -0.045701 -0.127980  
1      0.170288 -0.074533  0.296675 -0.332743  0.079091  0.080246 -0.422945  
2     -0.126657  0.070164 -0.095726  0.134546 -0.104331 -0.146242  0.301637  
3     -0.210256 -0.129064 -0.132808  0.509804 -0.054445 -0.107237  0.397015  
4      0.112444 -0.061797  0.436061 -0.141405  0.211014  0.104525 -0.198180  
...         ...       ...       ...       ...       ...       ...       ...  
13546  0.270955  0.021442  1.000000 -0.068214  0.257358  0.324740 -0.191356  
13547 -0.292163 -0.220228 -0.068214  1.000000 -0.090787 -0.098834  0.583108  
13548  0.069928 -0.026207  0.257358 -0.090787  1.000000  0.103404 -0.170155  
13549  0.286491  0.132001  0.324740 -0.098834  0.103404  1.000000 -0.040403  
13550 -0.177255  0.003180 -0.191356  0.583108 -0.170155 -0.040403  1.000000  

[13551 rows x 13551 columns]